### ISSUE TITLE
leg_detector launch files point to wrong map_laser files

### ISSUE THREAD

**Issue by cdondrup** [wg-perception/people#9]
The file `filtered_leg_detector.launch` tries to include:

```
<include file="$(find map_laser)/lfilter.launch"/>
```

Which does not exist in the current version of the map_laser package from the hydro repositories. The correct include would be:

```
<include file="$(find map_laser)/config/lfilter.launch"/>
```

The `shadows.launch` has a similar problem:

```
<rosparam command="load" file="$(find map_laser)/filters.yaml" />
```

Should be 

```
<rosparam command="load" file="$(find map_laser)/config/filters.yaml" />
```

to make it work with the current version of map_laser.

**Comment by DLu** [comment]
Thanks for the report. 

These are more a bug in map_laser, in that the install locations do not match the source locations. This was just  fixed in https://github.com/DLu/laser_filtering/commit/88d38737f51f1f24c384fbbf77519d1b14286f17

Until the next release, you can avoid the error by installing map_laser from source. 

Thanks again for the fix.
